
config setup
  charondebug="ike 2, knl 2, cfg 2"

conn site-to-site
  keyexchange=ikev1
  type=tunnel
  authby=psk
  auto=start

  left=10.10.10.1
  leftsubnet=192.168.10.0/24

  right=10.10.10.2
  rightsubnet=192.168.20.0/24

  ike=aes256-sha256-modp2048
  esp=aes256-sha256
